"""refactor model Category

Revision ID: bf488b3519d6
Revises: c33ffffe0109
Create Date: 2024-02-13 20:12:31.070029

"""
from typing import Sequence
from typing import Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "bf488b3519d6"
down_revision: Union[str, None] = "c33ffffe0109"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_category_name", table_name="category")
    op.create_index(op.f("ix_category_name"), "category", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_category_name"), table_name="category")
    op.create_index("ix_category_name", "category", ["name"], unique=False)
    # ### end Alembic commands ###
