"""refactor model Address

Revision ID: c33ffffe0109
Revises: cdaaf2577d84
Create Date: 2024-02-13 16:05:46.313128

"""
from typing import Sequence
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "c33ffffe0109"
down_revision: Union[str, None] = "cdaaf2577d84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
