"""refactor model Order

Revision ID: c81cd8321bc1
Revises: 0214fcbbb32f
Create Date: 2024-02-13 15:55:31.344129

"""
from typing import Sequence
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "c81cd8321bc1"
down_revision: Union[str, None] = "0214fcbbb32f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
