"""refactor model Product

Revision ID: cdaaf2577d84
Revises: c81cd8321bc1
Create Date: 2024-02-13 16:03:46.012072

"""
from typing import Sequence
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "cdaaf2577d84"
down_revision: Union[str, None] = "c81cd8321bc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
